# Configuration for finality gadget operator.

###############################################################
# The Common configs ##########################################
###############################################################
common:
  # the service name
  name: "operator-test"

  # used to set the logger level (true = info, false = debug)
  production: true

###############################################################
# The eth layer2 configs ######################################
###############################################################
layer2:
  # the http json rpc url of eth layer2
  eth_rpc_url: "http://10.1.1.39:8547"

  # the chain id of eth layer2, if not zero, will check if url 's chain id is eq
  chain_id: 412346

  # the activated_height number for layer2
  activated_height: 0

###############################################################
# The babylon configs ######################################
###############################################################
babylon:
  finality_gadget:
    # path to the DB file
    dbfilepath: "data.db"
    bitcoinrpchost: "10.1.1.120"
    bitcoinrpcuser: ""
    bitcoinrpcpass: ""
    bitcoindisabletls: true
    fgcontractaddress: "bbn1dvepyy7s2nkfep05c4v6tfkmzqyvz7x3nj6ddj3kkr8nfsmmylhq6a5yp4"

finalityProviderHomePath: "/fpd/"

# fp_addr is the bech32 chain address identifier of the finality provider.
fp_addr: "bbn1vd74qq3m49605j4k7ltnpxx3rweqvukcfp3esf"

# btc_pk is the BTC secp256k1 PK of the finality provider encoded in BIP-340 spec
btc_pk: "0x1648cb2885f24b25df13d49641cf9af8ebaece3753269e7d6ee33982953fda0b"

eotsManager:
  remote_address: "alt-blitz-eots-manager:12582"

metrics:
  host: "0.0.0.0"
  port: 2112
  updateinterval: 1s
