# Configuration for finality gadget operator.

###############################################################
# The Common configs ##########################################
###############################################################
common:
  # the service name
  name: "operator-test"

  # used to set the logger level (true = info, false = debug)
  production: false

###############################################################
# The eth layer2 configs ######################################
###############################################################
layer2:
  # the http json rpc url of eth layer2
  eth_rpc_url: "http://10.1.1.39:8547"

  # the chain id of eth layer2, if not zero, will check if url 's chain id is eq
  chain_id: 412346

  # the activated_height number for layer2
  activated_height: 32

###############################################################
# The babylon configs ######################################
###############################################################
babylon:
  finality_gadget:
    # rpc host address of the L2 node
    l2rpchost: "http://10.1.1.39:8547"
    # the nitro finality gadget contract address in babylon chain
    fgcontractaddress: "bbn17p9rzwnnfxcjp32un9ug7yhhzgtkhvl9jfksztgw5uh69wac2pgs6spw0g"
    # host:port to listen for gRPC connections
    grpclistener: "0.0.0.0:50051"
    # host:port to listen for HTTP connections
    httplistener: "0.0.0.0:8080"
    # the chain id of babylon chain
    bbnchainid: "my-testnet-01"
    # the rpc address url for babylon chain
    bbnrpcaddress: "http://10.1.1.39:26657"
    # The daemon's rpc listening address.
    bitcoinrpchost: "10.1.1.120:18443"
    # Username for RPC connections.
    bitcoinrpcuser: "test"
    # Password for RPC connections.
    bitcoinrpcpass: "123456"
    # disable TLS for RPC connections
    bitcoindisabletls: true
    # The time interval between each retry.
    pollinterval: "10s"
    # path to the DB file
    dbfilepath: "data.db"
  # The maximum number of peers staker will choose from the backend node to 
  # retrieve pruned blocks from. This only applies to pruned nodes.
  prunedNodeMaxpeers: 8
  # The interval that will be used to poll bitcoind for new blocks. Only used if rpcpolling is true.
  blockpollinginterval: "30s"
  # The interval that will be used to poll bitcoind for new tx. Only used if rpcpolling is true.
  txpollinginterval: "30s"
  # Size of the Bitcoin blocks cache.
  blockcachesize: 20971520
  # The max number of retries to an RPC call in case of failure.
  maxretrytimes: 5

finalityProviderHomePath: "/home/fy/fpd_home/"

###############################################################
# The fp configs ##############################################
###############################################################
finalityProvider:
  # The number of Schnorr public randomness for each commitment
  num_pub_rand: 3
  # The upper bound of the number of Schnorr public randomness for each commitment
  num_pub_rand_max: 8
  minrandheightgap: 35000
  # fp_addr is the bech32 chain address identifier of the finality provider.
  fp_addr: "bbn1vj7fa46npnlwnmclf7lygmu38qxjs8mx2e2ulx"
  # btc_pk is the BTC secp256k1 PK of the finality provider encoded in BIP-340 spec
  btc_pk: "0x577adbcb4a5f4857a29551888e85340efe40bac101ad8540e2cb374117f84d3f"
  # BabylonChain op finality gadget contract address
  fg_contract_address: "bbn17p9rzwnnfxcjp32un9ug7yhhzgtkhvl9jfksztgw5uh69wac2pgs6spw0g"
  # BabylonChain chain ID
  bbn_chain_id: "my-testnet-01"
  # BabylonChain chain RPC address
  bbn_rpc_address: "http://10.1.1.39:26657"
  cosmwasm:
    key: "fp"
    chain_id: "my-testnet-01"
    rpc_addr: "http://10.1.1.39:26657"
    grpc_addr: "http://10.1.1.39:9090"
    account_prefix: "bbn"
    keyring_backend: "test"
    gas_adjustment: 1.5
    gas_prices: "0.002ubbn"
    key_directory: "/home/fy/.blitz/keyring/"
    debug: true
    timeout: 20s
    block_timeout: 1m0s
    output_format: json
    sign_mode: direct
    submitter_address: "bbn1vj7fa46npnlwnmclf7lygmu38qxjs8mx2e2ulx"
  consumer_id: "test1"

eotsManager:
  remote_address: "10.1.1.120:12582"