# Configuration for finality gadget operator.

###############################################################
# The Common configs ##########################################
###############################################################
common:
  # the service name
  name: "operator-test"

  # used to set the logger level (true = info, false = debug)
  production: false

###############################################################
# The eth layer2 configs ######################################
###############################################################
layer2:
  # the http json rpc url of eth layer2
  eth_rpc_url: "http://127.0.0.1:8547"

  # the chain id of eth layer2, if not zero, will check if url 's chain id is eq
  chain_id: 412346

###############################################################
# The babylon configs ######################################
###############################################################
babylon:
  finality_gadget:
    # rpc host address of the L2 node
    l2rpchost: "http://127.0.0.1:8547"
    # the nitro finality gadget contract address in babylon chain
    fgcontractaddress: "http://127.0.0.1:8547"
    # host:port to listen for gRPC connections
    grpclistener: "0.0.0.0:50051"
    # host:port to listen for HTTP connections
    httplistener: "0.0.0.0:8080"
    # the chain id of babylon chain
    bbnchainid: "my-testnet-01"
    # the rpc address url for babylon chain
    bbnrpcaddress: "http://127.0.0.1:26657"
    # The daemon's rpc listening address.
    bitcoinrpchost: "rpc.ankr.com/btc"
    # Username for RPC connections.
    bitcoinrpcuser: "user"
    # Password for RPC connections.
    bitcoinrpcpass: "pass"
    # disable TLS for RPC connections
    bitcoindisabletls: false
    # The time interval between each retry.
    pollinterval: "10s"
    # path to the DB file
    dbfilepath: "data.db"
  # The maximum number of peers staker will choose from the backend node to 
  # retrieve pruned blocks from. This only applies to pruned nodes.
  prunedNodeMaxpeers: 8
  # The interval that will be used to poll bitcoind for new blocks. Only used if rpcpolling is true.
  blockpollinginterval: "30s"
  # The interval that will be used to poll bitcoind for new tx. Only used if rpcpolling is true.
  txpollinginterval: "30s"
  # Size of the Bitcoin blocks cache.
  blockcachesize: 20971520
  # The max number of retries to an RPC call in case of failure.
  maxretrytimes: 5
