# Configuration for finality gadget operator.

###############################################################
# The Common configs ##########################################
###############################################################
common:
  # the service name
  name: "operator-test"

  # used to set the logger level (true = info, false = debug)
  production: false

###############################################################
# The eth layer2 configs ######################################
###############################################################
layer2:
  # the http json rpc url of eth layer2
  eth_rpc_url: "http://10.1.1.49:8547"

  # the chain id of eth layer2, if not zero, will check if url 's chain id is eq
  chain_id: 412346

  # the activated_height number for layer2
  activated_height: 0

###############################################################
# The babylon configs ######################################
###############################################################
babylon:
  finality_gadget:
    # path to the DB file
    dbfilepath: "data.db"

finalityProviderHomePath: "/home/fy/.fpdback/"

# fp_addr is the bech32 chain address identifier of the finality provider.
fp_addr: "bbn1tvt7058xrce9r3helj9ym0xa08jvaedd543pdm"

# btc_pk is the BTC secp256k1 PK of the finality provider encoded in BIP-340 spec
btc_pk: "0x28252efa5097e0b007dca2d11308c5670e6e822ba39d8dd0ab0c88111ec2b7e3"

eotsManager:
  remote_address: "10.1.1.120:12582"

metrics:
  host: "0.0.0.0"
  port: 2112
  updateinterval: 1s
